
# “cards” de destaque (para profile README ou hubs)
REPO_TAGLINE: Quantum simulation • electronic structure • many-body systems

# caminho local de saída (se quiser fixar)
README_OUT: README.md
ASSETS_DIR: .github/readme

CTA_TEXT: Upcoming topic...

THEME: board

# Cores (SVG tokens)
BG_1: "#0b1220"
BG_2: "#111827"
TEXT_MAIN: "#e5e7eb"
TEXT_MUTED: "#9ca3af"
ACCENT: "#93c5fd"

# (opcionais, se você for usar no SVG)
CARD_RADIUS: "18"
