
# “cards” de destaque (para profile README ou hubs)
REPO_TAGLINE: Quantum simulation • electronic structure • many-body systems

# caminho local de saída (se quiser fixar)
README_OUT: README.md
ASSETS_DIR: .github/readme

CTA_TEXT: Upcoming topic...

THEME: board

SITE_URL: https://academic-codex.github.io/PGF5002-Mecanica-Quantica-II

BG_1: "#000000"
BG_2: "#000000"

TEXT_MAIN: "#999999"
TEXT_MUTED: "#303030"
ACCENT: "#555555"

CARD_RADIUS: "5"
