
# “cards” de destaque (para profile README ou hubs)
REPO_TAGLINE: Quantum simulation • electronic structure • many-body systems

# caminho local de saída (se quiser fixar)
README_OUT: README.md
ASSETS_DIR: .github/readme

CTA_TEXT: Upcoming topic...

THEME: coding


BG_1: "#FFFF00"
BG_2: "#FFFF00"

TEXT_MAIN: "#FFFF00"
TEXT_MUTED: "#FFFF00"
ACCENT: "#FFFF00"

CARD_RADIUS: "30"
