
# “cards” de destaque (para profile README ou hubs)
REPO_TAGLINE: Quantum simulation • electronic structure • many-body systems

# caminho local de saída (se quiser fixar)
README_OUT: README.md
ASSETS_DIR: .github/readme

CTA_TEXT: Upcoming topic...

THEME: board


BG_1: "#3f4f2f"
BG_2: "#2f3a23"

TEXT_MAIN: "#f3f4f2"
TEXT_MUTED: "#c7cbbf"
ACCENT: "#9ecae1"

CARD_RADIUS: "18"
